select * from [dbo].[Fact]
select * from [dbo].[Opportunity]
select * from [dbo].[Account]
---------------- REGION WISE OPPORTUNITY ----------------------
SELECT REGION,COUNT(OPPORTUNITY_ID)AS TOTAL_OPPORTUNITY
FROM FACT 
JOIN
Account
ON FACT.Account_ID = ACCOUNT.Account_ID 
GROUP BY Region
----------------- TOTAL OPPORTUNITY ---------------------
SELECT COUNT(OPPORTUNITY_ID)
FROM FACT

--------------------- REGION & SALES STAGE WISE OPPORTUNITY--------------------
CREATE VIEW VW_ACCOUNT_FACT AS
SELECT REGION,OPPORTUNITY_ID,SALES_STAGE_ID
FROM FACT
JOIN
ACCOUNT
ON FACT.Account_ID = ACCOUNT.Account_ID

SELECT REGION,SALES_STAGE,COUNT(OPPORTUNITY_ID) AS TOTAL_OPPORTUNITY
FROM VW_ACCOUNT_FACT
JOIN
[dbo].[Sales Stage]
ON VW_ACCOUNT_FACT.SALES_STAGE_ID = [dbo].[Sales Stage].SALES_STAGE_ID
GROUP BY REGION,SALES_STAGE

--------------------- OPPORTUNITY SIZE AND REGION WISE OPPORTUNITY---------------

SELECT REGION,OPPORTUNITY_SIZE,COUNT(Name) AS TOTAL_OPPORTUNITY
FROM VW_ACCOUNT_FACT
JOIN
Opportunity
ON VW_ACCOUNT_FACT.Opportunity_ID = OPPORTUNITY.Opportunity_ID
GROUP BY REGION,OPPORTUNITY_SIZE;
--------------------------------- OPPORTUNITY BY PARTNER DRIVEN---------------
SELECT PARTNER_DRIVEN,COUNT(OPPORTUNITY_ID) AS TOTAL_OPPORTUNITY
FROM FACT
JOIN
PARTNER
ON FACT.Partner_ID = PARTNER.[Partner ID]
GROUP BY Partner_Driven

------------------------- REVENUE BY REGION---------------------
SELECT REGION,SUM(PRODUCT_REVENUE) AS TOTAL_REVENUE FROM FACT
JOIN
ACCOUNT
ON FACT.Account_ID = ACCOUNT.Account_ID
GROUP BY REGION;

----------------REVENUE BY SALES STAGE & PARTNER DRIVEN ---------------
CREATE VIEW VW_REVENUE_SALESSTAGE_OPPORTUNITY AS
SELECT PRODUCT_REVENUE,Partner_ID,SALES_STAGE,Opportunity_ID
FROM FACT
JOIN
[Sales Stage]
ON FACT.Sales_Stage_ID = [Sales Stage].Sales_Stage_ID

SELECT SALES_STAGE,PARTNER_DRIVEN,SUM(PRODUCT_REVENUE) AS TOTAL_REVENUE
FROM Partner
JOIN
VW_REVENUE_SALESSTAGE
ON Partner.PARTNER_ID =VW_REVENUE_SALESSTAGE.Partner_ID
GROUP BY SALES_STAGE,PARTNER_DRIVEN;

--------------------- AVERAGE REVENUE BY PARTNER DRIVEN & SALES STAGE ----------------
SELECT PARTNER_DRIVEN,SALES_STAGE, AVG(PRODUCT_REVENUE) AS AVERAGE_REVENUE
FROM VW_REVENUE_SALESSTAGE_OPPORTUNITY
JOIN
Partner
ON VW_REVENUE_SALESSTAGE_OPPORTUNITY.Partner_ID = Partner.PARTNER_ID
GROUP BY PARTNER_DRIVEN,Sales_Stage;

---------------------------AVERAGE REVENUE BY PARTNER DRIVEN & OPPORTUNITY_SIZE ---------------
CREATE VIEW VW_REVENUE_PARTNER AS
SELECT PRODUCT_REVENUE,PARTNER_DRIVEN,Opportunity_ID
FROM FACT
JOIN
Partner
ON FACT.Partner_ID = Partner.PARTNER_ID

SELECT PARTNER_DRIVEN,OPPORTUNITY_SIZE,AVG(PRODUCT_REVENUE) AS AVERAGE_REVENUE
FROM VW_REVENUE_PARTNER
JOIN
Opportunity
ON VW_REVENUE_PARTNER.Opportunity_ID = Opportunity.Opportunity_ID
GROUP BY PARTNER_DRIVEN,OPPORTUNITY_SIZE;
---------------------REVENUE,FACTOR REVENUE ----------------
SELECT SUM(PRODUCT_REVENUE) AS TOTAL_REVENUE,
SUM(FactoredProductRevenue)AS TOTAL_FACTORED_REVENUE
FROM FACT
-----------------------FACTORED REVENUE BY OPPORTUNITY SIZE ---------------
SELECT OPPORTUNITY_SIZE,SUM(FactoredProductRevenue)AS TOTAL_FACTORED_REVENUE
FROM FACT
JOIN
Opportunity
ON FACT.Opportunity_ID = Opportunity.Opportunity_ID
GROUP BY Opportunity_Size;

------------------------OPPORTUNITY COUNT BY MONTH & SALES STAGE ------------------
SELECT MONTH,SALES_STAGE,COUNT(OPPORTUNITY_ID) AS NUM_OF_OPPORTUNITY
FROM FACT
JOIN
[Sales Stage]
ON FACT.Sales_Stage_ID = [Sales Stage].Sales_Stage_ID
GROUP BY MONTH,SALES_STAGE;

-------------------OPPORTUNITY COUNT BY PARTNER DRIVEN & SALES STAGE---------------
SELECT SALES_STAGE,PARTNER_DRIVEN,COUNT(OPPORTUNITY_ID) AS NUM_OF_OPPORTUNITY
FROM VW_REVENUE_SALESSTAGE_OPPORTUNITY
JOIN
Partner
ON VW_REVENUE_SALESSTAGE_OPPORTUNITY.Partner_ID = Partner.PARTNER_ID
GROUP BY SALES_STAGE,PARTNER_DRIVEN;

-----------------------------------------------------------------------------


