SELECT * FROM TV_DATA

------------------ BRAND WISE REVENUE--------------
SELECT BRAND,SELLING_PRICE,SUM(SELLING_PRICE)
OVER(PARTITION BY BRAND ORDER BY BRAND) AS TOTAL_PRICE
FROM TV_DATA

-------------BRAND WISE TOTAL SELL--------------
SELECT BRAND,SELLING_PRICE,COUNT(BRAND)
OVER(PARTITION BY BRAND ORDER BY BRAND) AS TOTAL_SELL
FROM TV_DATA

------------------SIZE WISE REVENUE -----------------
SELECT BRAND,SIZE, SELLING_PRICE,SUM(SELLING_PRICE)
OVER(PARTITION BY SIZE ORDER BY SIZE)AS TOTAL_PRICE
FROM TV_DATA

--------------------SIZE WISE SELL-------------
SELECT BRAND,SIZE,COUNT(SIZE)
OVER(PARTITION BY SIZE ORDER BY SIZE)AS TOTAL_SELL
FROM TV_DATA

----------------RESOLUTION AND OPERATING SYSTEM WISE REVENUE--------------
SELECT BRAND,RESOLUTION,OPERATING_SYSTEM,SUM(SELLING_PRICE)
OVER(PARTITION BY RESOLUTION,OPERATING_SYSTEM)
FROM TV_DATA

----------------RESOLUTION AND OPERATION SYSTEM WISE SELL----------------
SELECT BRAND,RESOLUTION,OPERATING_SYSTEM,COUNT(BRAND)
OVER(PARTITION BY RESOLUTION,OPERATING_SYSTEM)
FROM TV_DATA

------------------RATING WISE SELL--------------------
SELECT BRAND,RATING,SUM(SELLING_PRICE) 
OVER(PARTITION BY RATING)AS TOTAL_SALE 
FROM TV_DATA
UPDATE TV_DATA
SET RATING = 0
WHERE RATING IS NULL

-----------------TOP 3 BRAND RESPECT TO HIGHEST SELL------------------
SELECT TOP 3 BRAND,COUNT(BRAND)AS TOTAL_SELL_AMOUNT
FROM TV_DATA
GROUP BY BRAND
ORDER BY TOTAL_SELL_AMOUNT DESC

---------------TOP 3 BRAND WITH RESPECT TO RATING---------------------
SELECT TOP 3 RATING,BRAND
FROM TV_DATA
ORDER BY RATING DESC

------------TOTAL SELLING PRICE-------------
SELECT SUM(SELLING_PRICE) FROM TV_DATA


-------------TOTAL NUMBER OF SELL--------------
SELECT COUNT(BRAND) FROM TV_DATA

