----------------------AIRLINE CUSTOMER ANALYSIS---------------

SELECT * FROM customer_booking

------------------- SALES CHANNEL WISE CUSTOMER ------------------
SELECT SALES_CHANNEL,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGERS
FROM customer_booking
GROUP BY sales_channel;

----------------------------- TRIP TYPE WISE CUSTOMER-----------------
SELECT trip_type,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGERS
FROM customer_booking
GROUP BY trip_type;
------------------------------- STAY LENGTH WISE CUSTOMER & highest stay length -----------
SELECT trip_type,LENGTH_OF_STAY,SUM(NUM_PASSENGERS)  
OVER(PARTITION BY LENGTH_OF_STAY,TRIP_TYPE)AS TOTAL_PASSENGERS
FROM customer_booking

WITH CTC_TRIP_STAY AS
(
SELECT trip_type,LENGTH_OF_STAY,SUM(NUM_PASSENGERS)  
OVER(PARTITION BY LENGTH_OF_STAY,TRIP_TYPE)AS TOTAL_PASSENGERS
FROM customer_booking
)
SELECT TRIP_TYPE,LENGTH_OF_STAY,TOTAL_PASSENGERS FROM CTC_TRIP_STAY
WHERE TOTAL_PASSENGERS=
(SELECT MAX(TOTAL_PASSENGERS) 
FROM CTC_TRIP_STAY);
------------------------ DAY WISE CUSTOMER & DAY WHEN MAXIMUM BOOKING IS DONE----------------
SELECT FLIGHT_DAY,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
FROM customer_booking
GROUP BY FLIGHT_DAY;


WITH CTC_DAY_PASSENGER AS
(
SELECT FLIGHT_DAY,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
FROM customer_booking
GROUP BY FLIGHT_DAY
)
SELECT FLIGHT_DAY,TOTAL_PASSENGER FROM CTC_DAY_PASSENGER
WHERE TOTAL_PASSENGER =
(SELECT MAX(TOTAL_PASSENGER) AS HIGH_PASSENGER 
FROM CTC_DAY_PASSENGER);
------------------------ HOUR WISE CUSTOMER & HOUR WHEN MAXIMUM BOOKING IS DONE----------------
SELECT FLIGHT_HOUR,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
FROM customer_booking
GROUP BY FLIGHT_HOUR;


WITH CTC_HOUR_PASSENGER AS
(
SELECT FLIGHT_HOUR,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
FROM customer_booking
GROUP BY FLIGHT_HOUR
)
SELECT FLIGHT_HOUR,TOTAL_PASSENGER FROM CTC_HOUR_PASSENGER
WHERE TOTAL_PASSENGER =
(SELECT MAX(TOTAL_PASSENGER) AS HIGH_PASSENGER 
FROM CTC_HOUR_PASSENGER);
------------------------------ ROUTE WISE CUSTOMER & POPULAR ROUTE ---------
SELECT route,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
FROM customer_booking
GROUP BY route;


WITH CTC_ROUTE_PASSENGER AS
(
SELECT route,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
FROM customer_booking
GROUP BY route
)
SELECT route,TOTAL_PASSENGER FROM CTC_ROUTE_PASSENGER
WHERE TOTAL_PASSENGER =
(SELECT MAX(TOTAL_PASSENGER) AS HIGH_PASSENGER
FROM CTC_ROUTE_PASSENGER);
---------------TOP 3 ROUTE-----------------
WITH CTC_ROUTE_PASSENGER AS
(
SELECT route,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
FROM customer_booking
GROUP BY route
)
 SELECT TOP 3 ROUTE 
 FROM CTC_ROUTE_PASSENGER 
 ORDER BY TOTAL_PASSENGER DESC;
 ----------------------------- NUMBER OF PASSENGE WANTS EXTRA BAGGAGE ------------------
 SELECT
 SUM(NUM_PASSENGERS) AS TOTAL_PASSENGERS_WANTS_EXTRA_BAGGAGE
 FROM customer_booking 
 WHERE wants_extra_baggage = 1
 

-------------------------------NUMBER OF PASSENGER WANTS PREFERRED SEAT-----------------
  SELECT SUM(NUM_PASSENGERS) AS TOTAL_PASSENGERS_WANTS_PREFERRED_SEAT
 FROM customer_booking 
 WHERE wants_preferred_seat = 1
 ---------------------------------NUMBER OF PASSENGERS WANTS IN FLIGHT MEAL -------------------

  SELECT SUM(NUM_PASSENGERS) AS TOTAL_PASSENGERS_WANTS_IN_FLIGHT_MEALS
 FROM customer_booking 
 WHERE wants_in_flight_meals = 1
 -------------------------------------------
 SELECT * FROM customer_booking
 -------------------------------- TOTAL CUSTOMER ----------------------
 SELECT SUM(CONVERT(INT,NUM_PASSENGERS)) AS TOTAL_PASSENGERS
 FROM [dbo].[customer_booking]
 ----------------------------FLIGHT DURATION WISE PASSENGER---------------
 SELECT FLIGHT_DURATION,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
 FROM [dbo].[customer_booking]
 GROUP BY FLIGHT_DURATION
------------------------------- TIME DURATION AND NO OF PASSENGERS WHEN MOST OF THE PASSENGER TRAVEL-----------------
 WITH CTC_DURATION_PASSENGER AS
 (
  SELECT FLIGHT_DURATION,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
 FROM [dbo].[customer_booking]
 GROUP BY FLIGHT_DURATION
 )
 SELECT FLIGHT_DURATION,TOTAL_PASSENGER FROM CTC_DURATION_PASSENGER
 WHERE TOTAL_PASSENGER =
 (SELECT MAX(TOTAL_PASSENGER)
 FROM CTC_DURATION_PASSENGER)
 ----------------------------------------- NUMBER OF BOOKING -------------------
 SELECT COUNT(BOOKING_COMPLETE) AS TOTAL_BOOKING
 FROM customer_booking
 WHERE booking_complete = 1
 
 ---------------- COUNTRY WISE BOOKING ------------------------
 SELECT booking_origin,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
 FROM [dbo].[customer_booking]
 GROUP BY booking_origin;
---------------- TOP 3 COUNTRY FROM WHERE MOST OF THE BOOKING DONE -----------------
  WITH CTC_COUNTRY_PASSENGER AS
 (
  SELECT booking_origin,SUM(NUM_PASSENGERS) AS TOTAL_PASSENGER
 FROM [dbo].[customer_booking]
 GROUP BY booking_origin
 )
 SELECT TOP 3 booking_origin,TOTAL_PASSENGER
 FROM CTC_COUNTRY_PASSENGER
 ORDER BY TOTAL_PASSENGER DESC;

 ----------------------- MAXIMUM AND MINIMUM DAY BETWEEN BOOKING AND TRAVELLING----------------
 SELECT MAX(PURCHASE_LEAD) AS MAX_DAY,MIN(PURCHASE_LEAD) AS MIN_DAY
 FROM customer_booking;
 
 SELECT * FROM customer_booking


 